baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My Blog'
theme = 'ananke'
paginate = 12

[params]
  mainSections = ['posts']
  description = 'A collection of notes, thoughts, and learnings.'

[params.ananke]
  show_recent_posts = true

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 4
  ordered = false

ignoreLogs = ['warning-goldmark-raw-html']

[outputs]
  home = ['HTML', 'RSS', 'JSON']
